# Generated by Django 4.1.3 on 2023-09-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phonenumber_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
