# Generated by Django 4.1.3 on 2023-08-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='normal_user',
            new_name='user',
        ),
    ]
