# Generated by Django 4.1.3 on 2023-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
