# Generated by Django 4.1.3 on 2023-09-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_alter_receipttask_receipt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('accepted', 'تایید شده'), ('pending', 'در صف'), ('rejected', 'رد شده')], max_length=15),
        ),
    ]
