# Generated by Django 4.1.3 on 2023-10-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0014_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='receipt.project'),
            preserve_default=False,
        ),
    ]
