# Generated by Django 4.1.3 on 2023-09-12 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import receipt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('progress_percentage', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'تایید شده'), ('pending', 'در صف'), ('rejected', 'رد شده')], default='pending', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('picture', models.ImageField(max_length=3000, upload_to=receipt.models.upload_receipt_pic_src)),
                ('submited_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checked', 'بررسی شده'), ('pending', 'نیاز به بررسی'), ('rejected', 'رد شده')], default='pending', max_length=15)),
                ('description_task', models.TextField(blank=True, null=True)),
                ('receipt_status', models.CharField(choices=[('accepted', 'تایید شده'), ('rejected', 'رد شده')], max_length=15)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='receipt.receipt')),
                ('user_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admin', to=settings.AUTH_USER_MODEL)),
                ('user_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_super_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
