# Generated by Django 4.1.3 on 2023-09-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipttask',
            name='status',
            field=models.CharField(choices=[('accepted', 'بررسی شده'), ('pending', 'نیاز به بررسی'), ('rejected', 'رد شده')], default='pending', max_length=15),
        ),
    ]
