# Generated by Django 4.1.3 on 2023-09-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_alter_receipt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipttask',
            name='status',
            field=models.CharField(choices=[('accepted', 'بررسی شده'), ('pending', 'نیازمند بررسی مدیر'), ('rejected', 'رد شده')], default='pending', max_length=15),
        ),
    ]
