# Generated by Django 4.1.3 on 2023-09-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_alter_receipttask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('-id',)},
        ),
    ]
