# Generated by Django 4.1.3 on 2023-09-16 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0007_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='progress_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
