# Generated by Django 4.1.3 on 2023-09-26 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_alter_building_progress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='bank_name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='deposit_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='depositor_name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
