# Generated by Django 3.2 on 2024-06-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0015_building_project_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('-id',), 'permissions': (('set_available_building', 'Can set available buildings'),)},
        ),
        migrations.AlterModelOptions(
            name='receipttask',
            options={'permissions': (('view_in_user_detail_receipt_tasks', 'Can access to receipt tasks in user detail page'),)},
        ),
    ]
