# Generated by Django 3.2 on 2024-06-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0016_auto_20240609_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('-id',), 'permissions': (('view_full_building', 'Can view all buildings'), ('view_admin_building', 'Can view admin buildings'), ('view_user_building', 'Can view user buildings'))},
        ),
        migrations.AlterModelOptions(
            name='buildingavailable',
            options={'permissions': (('set_available_building', 'Can set available building'),)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_full_project', 'Can view all projects'),)},
        ),
    ]
