# Generated by Django 3.2 on 2024-06-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0017_auto_20240612_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('-id',), 'permissions': (('view_full_building', 'Can view all buildings'), ('view_admin_building', 'Can view admin buildings'), ('view_user_building', 'Can view user buildings'), ('view_financial_building', 'Can view financial part(amount,chart and ..) buildings'), ('view_receipts_building', 'Can view receipts buildings'), ('view_users_building', 'Can view users buildings'), ('view_users_score_building', 'Can view users score buildings'), ('export_building', 'Can export all data of buildings'))},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'permissions': (('auto_accept_receipt', 'Accept receipt automatically'), ('view_full_receipts', 'Can view all receipts'), ('view_admin_receipts', 'Can view receipts submited by self'), ('view_user_receipts', 'Can view receipts submited by self'))},
        ),
    ]
