# Generated by Django 3.2 on 2024-06-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0018_auto_20240613_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'permissions': (('auto_accept_receipt', 'Accept receipt automatically'), ('view_full_receipts', 'Can view all receipts'), ('view_admin_receipts', 'Can view receipts submited by self (admin)'), ('view_user_receipts', 'Can view receipts submited by self (user)'))},
        ),
    ]
