# Generated by Django 3.2 on 2024-06-15 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0019_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'permissions': (('auto_accept_receipt', 'Accept receipt automatically'), ('view_full_receipts', 'Can view all receipts'), ('view_admin_receipts', 'Can view receipts submited by (admin)'), ('view_user_receipts', 'Can view receipts submited by (user)'))},
        ),
        migrations.AlterModelOptions(
            name='receipttask',
            options={'permissions': (('view_full_receipts_task', 'Can view all receipts task'), ('view_in_user_detail_receipt_tasks', 'Can access to receipt tasks in user detail page'), ('view_admin_receipt_task', 'Can access to receipt tasks user by admin role'))},
        ),
        migrations.RemoveField(
            model_name='receipttask',
            name='user_super_admin',
        ),
        migrations.AddField(
            model_name='receipttask',
            name='user_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='receipttask',
            name='receipt_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=15),
        ),
        migrations.AlterField(
            model_name='receipttask',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Need to check by supervisor'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
