# Generated by Django 3.2 on 2024-06-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0020_auto_20240615_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'permissions': (('change_full_receipt', 'User can edit all receipt'), ('auto_accept_receipt', 'Accept receipt automatically'), ('user_accept_receipt', 'User can accept receipt'), ('user_reject_receipt', 'User can reject receipt'), ('view_full_receipts', 'Can view all receipts'), ('view_admin_receipts', 'Can view receipts submited by (admin)'), ('view_user_receipts', 'Can view receipts submited by (user)'), ('view_ratio_score_receipt', 'Can view ratio score receipt'), ('set_ratio_score_receipt', 'Can set ratio score receipt'))},
        ),
        migrations.AlterModelOptions(
            name='receipttask',
            options={'permissions': (('view_full_receipts_task', 'Can view all receipts task'), ('view_in_user_detail_receipt_tasks', 'Can access to receipt tasks in user detail page'), ('view_admin_receipt_task', 'Can access to receipt ta sks user by admin role'), ('user_accept_receipt_task', 'User can accept receipt task'), ('user_reject_receipt_task', 'User can reject receipt task'))},
        ),
    ]
