# Generated by Django 4.2 on 2024-06-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0022_alter_receipttask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='picture_hash',
            field=models.CharField(blank=True, max_length=65, null=True, unique=True),
        ),
    ]
