# Generated by Django 4.2 on 2024-06-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0023_receipt_picture_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='picture_hash',
        ),
    ]
