# Generated by Django 4.1.3 on 2023-08-13 21:49

import core.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_file_created_at_remove_file_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=400, upload_to=core.models.base.upload_file_src),
        ),
    ]
