# Generated by Django 4.1.3 on 2023-09-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_file_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
