# Generated by Django 4.1.3 on 2023-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_ticketreplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='degree_of_importance',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], max_length=30),
        ),
    ]
