# Generated by Django 4.1.3 on 2023-09-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_question_answerquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
