# Generated by Django 4.1.3 on 2023-09-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer',
            field=models.CharField(choices=[('option_1', 'گزینه یکم'), ('option_2', 'گزینه دوم'), ('option_3', 'گزینه سوم'), ('option_4', 'گزینه چهارم')], max_length=100),
        ),
    ]
