# Generated by Django 3.2 on 2024-06-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_alter_answerquestion_options_question_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-id',), 'permissions': (('export_data_question', 'Can export data of question'),)},
        ),
    ]
