# Generated by Django 4.1.3 on 2023-08-11 19:24

from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationuser_is_showing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attach',
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=notification.models.upload_notification_src),
        ),
    ]
