# Generated by Django 4.1.3 on 2023-08-11 19:56

from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_attach_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=notification.models.upload_notification_src),
        ),
    ]
