# Generated by Django 4.1.3 on 2023-08-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-is_active', '-id')},
        ),
        migrations.AlterModelOptions(
            name='notificationuser',
            options={'ordering': ('-id',)},
        ),
    ]
