# Generated by Django 4.1.3 on 2023-09-14 11:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notificationuser_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='link',
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='kwargs',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
