# Generated by Django 4.1.3 on 2023-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal_user', 'کاربر عادی'), ('financial_user', 'ادمین مالی'), ('super_user', 'ادمین وِیژه')], default='normal_user', max_length=20),
        ),
    ]
