# Generated by Django 3.2 on 2024-06-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_phonenumber_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'permissions': (('view_full_user', 'Can view all user'), ('export_list_user', 'Can export data list of users'))},
        ),
    ]
