# Generated by Django 3.2 on 2024-06-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('common_user', 'Common user'), ('admin_user', 'Admin user'), ('super_user', 'Super user')], default='common_user', max_length=20),
        ),
    ]
