# Generated by Django 3.2 on 2024-06-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'permissions': (('view_full_user', 'Can view all user'), ('export_list_user', 'Can export data list of users'), ('change_self_user', 'Can change self info'), ('set_permission_user', 'Can set permission on user'), ('create_admin_user', 'Can create admin user'))},
        ),
    ]
