# Generated by Django 4.1.3 on 2023-08-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_degree_of_importance_ticket_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReplay',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='support.ticket')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replay', to='support.ticket')),
            ],
            options={
                'abstract': False,
            },
            bases=('support.ticket',),
        ),
    ]
