# Generated by Django 4.1.3 on 2023-08-13 21:49

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_ticket_is_open_alter_ticket_degree_of_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=support.models.upload_file_src),
        ),
    ]
