# Generated by Django 4.1.3 on 2023-09-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_alter_answerquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
