# Generated by Django 4.1.3 on 2023-10-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0016_project_description'),
        ('support', '0011_alter_answerquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipt.building'),
        ),
    ]
