# Generated by Django 4.1.3 on 2023-10-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_question_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestion',
            options={'ordering': ('-id',)},
        ),
    ]
