# Generated by Django 4.1.3 on 2023-09-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='send_notify',
            field=models.BooleanField(default=True),
        ),
    ]
