# Generated by Django 3.2 on 2024-06-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_remove_notificationuser_link_notificationuser_kwargs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationuser',
            options={'ordering': ('-id',), 'permissions': (('create_building_notification_user', 'Can create notification for users of building'),)},
        ),
    ]
