# Generated by Django 4.1.3 on 2023-08-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
    ]
